# Generated by Django 3.1.4 on 2021-05-15 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_content',
            field=models.TextField(default='blank'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogs',
            name='title',
            field=models.TextField(default='blank'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='writer',
            field=models.TextField(default='blank'),
        ),
    ]
