# Generated by Django 3.1.4 on 2021-05-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210515_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='link',
            field=models.TextField(default='https://auraed.medium.com/'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='blog_content',
            field=models.TextField(default='40 words'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='writer',
            field=models.TextField(default='AuraEd'),
        ),
    ]
