# Generated by Django 3.1.4 on 2021-05-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210515_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='Kathmandu')),
                ('image', models.ImageField(upload_to='albums')),
                ('img_filter', models.TextField(default='all for all,hpde for digital literacy,sprinkle for child education and spray for fundraising')),
            ],
        ),
    ]
