# Generated by Django 3.1.4 on 2021-05-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_albums'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(upload_to='team')),
                ('position', models.CharField(default='Member', max_length=50)),
                ('facebook', models.CharField(default='#', max_length=150)),
                ('twitter', models.CharField(default='#', max_length=150)),
                ('linkedin', models.CharField(default='#', max_length=150)),
                ('github', models.CharField(default='#', max_length=150)),
                ('description', models.CharField(default='2 or 3 words', max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='albums',
            name='img_filter',
            field=models.TextField(default='all for all,hpde for digital literacy,sprinkle for child education and spray for workshop'),
        ),
    ]
