# Generated by Django 3.1.4 on 2021-05-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210515_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='website',
            field=models.CharField(default='#', max_length=150),
        ),
    ]
