# Generated by Django 3.1.4 on 2021-05-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_teams_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='albums',
            name='img_filter',
            field=models.TextField(default='all for all,hpde for digital literacy,sprinkle for child education and spray for workshop', max_length=100),
        ),
        migrations.AlterField(
            model_name='albums',
            name='location',
            field=models.CharField(default='Kathmandu', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='link',
            field=models.CharField(default='https://auraed.medium.com/', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.CharField(default='blank', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='writer',
            field=models.CharField(default='AuraEd', max_length=50),
        ),
    ]
